// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubjectTopicsApp.Models;

#nullable disable

namespace SubjectTopicsApp.Migrations
{
    [DbContext(typeof(SubjectTopicsDbContext))]
    partial class SubjectTopicsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubjectTopicsApp.Models.SubjectTopic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TopicId")
                        .HasName("PK__SubjectT__022E0F5D271ADA1F");

                    b.ToTable("SubjectTopics");
                });

            modelBuilder.Entity("SubjectTopicsApp.Models.Subtopic", b =>
                {
                    b.Property<int>("SubtopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubtopicId"));

                    b.Property<string>("SubtopicName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("SubtopicId")
                        .HasName("PK__Subtopic__C73C3606EDBD622A");

                    b.HasIndex("TopicId");

                    b.ToTable("Subtopics");
                });

            modelBuilder.Entity("SubjectTopicsApp.Models.Subtopic", b =>
                {
                    b.HasOne("SubjectTopicsApp.Models.SubjectTopic", "Topic")
                        .WithMany("Subtopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Subtopics__Topic__38996AB5");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SubjectTopicsApp.Models.SubjectTopic", b =>
                {
                    b.Navigation("Subtopics");
                });
#pragma warning restore 612, 618
        }
    }
}
